services:
  - type: web
    name: detectoria-backend
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --chdir backend --workers 4 --timeout 120 --access-logfile - app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
